---
name: Check formatting

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update
        run: sudo apt-get update

      - name: Install clang-format
        run: sudo apt-get -y install clang-format

      - name: Check formatting
        run: ./tools/check-formatting.sh
